new CommonSourceDatasetMeasurements and MeasurementPairs classes crea…
NetherlandsForensicInstitute/lr-benchmark pull request #16
Opened 2024-01-15 15:18 UTC by GorkaLeonie

new CommonSourceDatasetMeasurements and MeasurementPairs classes created to overcome overflow of if-else statements

2024-01-16 08:33 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
> +class CommonSourceDataset(Dataset, ABC):
for general discussion; i dont think common source is a property of a dataset, but of how you handle the dataset. suggest to remove this in-between class (other PR)

2024-01-16 08:34 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
>          self.n_splits = n_splits
why is n_splits a property of the object, and not a parameter of calling get_splits?

2024-01-16 09:17 UTC, rolfypma-nfi requested changes
I think splitting these two datasets makes sense!

2024-01-16 09:17 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
> +    def get_x_y_pairs(self, transformer: Optional[Callable] = AbsDiffTransformer) -> XYType:
it's very confusing to have 2 get_x_y functions. Can we make it one function that checks whether any computation needs to be done? I would suggest leaving the transformation to whoever call this, and let the dataset just provide the data

2024-01-16 09:17 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
> +class XTCDataset(CommonSourceDataset):
```suggestion
class XTCDataset(CommonSourceDatasetMeasurements):
```

2024-01-16 15:57 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
>          self.n_splits = n_splits
fixed by removing n_splits all together and hard-coding this to the value 1 for the splits.

2024-01-16 15:58 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +        return set([m.source.id for m in self.measurements])
changed

2024-01-16 15:59 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
>      def get_x_measurement(self) -> np.ndarray:
adopted

2024-01-16 15:59 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
>      def get_x_y_measurement(self) -> XYType:
adopted

2024-01-16 16:02 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +                           absolute amount of measurements, measurement pairs or groups in each split.  If not
adopted

2024-01-16 16:03 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +                          absolute amount of measurements, measurement pairs or groups in each split. If not specified,
adopted

2024-01-16 16:04 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +        yield from self.get_splits_measurements(group_by_source, stratified, train_size, test_size, seed)
fixed

2024-01-17 07:40 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
> +            s = ShuffleSplit(n_splits=1, random_state=seed, train_size=train_size, test_size=test_size)
n_splits=1 may not be the expected behaviour :)
make  n_splits a parameter of the function?

2024-01-17 07:41 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
> +        split = s.split(self.measurements, groups=source_ids)[0]
why only take the first split?

2024-01-17 07:42 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
>      def get_splits(self, stratified: bool = False, group_by_source: bool = False,
dont forget to remove this one

2024-01-17 08:45 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
> +            self.load()
in other PR

2024-01-17 09:06 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +            self.load()
in other PR

2024-01-17 09:06 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +        :param stratified: boolean that indicates whether the dataset should be split while preserving the ratio of
in other PR

2024-01-17 09:08 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +                   train_size: Optional[Union[float, int]] = 0.8, test_size: Optional[Union[float, int]] = 0.2,
in other PR

2024-01-17 09:13 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +            self.load()
in other PR

2024-01-17 09:33 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +            s = ShuffleSplit(n_splits=1, random_state=seed, train_size=train_size, test_size=test_size)
adopted

2024-01-17 09:33 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +        split = s.split(self.measurements, groups=source_ids)[0]
resolved

2024-01-17 13:19 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +    def get_x_y_pairs(self,
task created in backlog

2024-01-17 13:19 UTC, GorkaLeonie commented on lrbenchmark/data/dataset.py
> +    def get_x_y_pairs(self, transformer: Optional[Callable] = AbsDiffTransformer) -> XYType:
task created in backlog

2024-01-17 13:29 UTC, rolfypma-nfi commented on lrbenchmark/data/dataset.py
>      def get_x_y_pairs(self,
deze dan ook gewoon get_x_y?

2024-01-17 13:30 UTC, rolfypma-nfi approved these changes

2024-01-17 15:03 UTC, merged