Provide multiple properties to run case comparisons at once
NetherlandsForensicInstitute/lr-benchmark pull request #45
Opened 2024-02-07 12:46 UTC by cdwagenaar

2024-02-07 13:14 UTC, rolfypma-nfi commented on config/data/asr.yaml
> -  trace_properties:
it seems odd to define experiments in the data file?

2024-02-07 15:04 UTC, cdwagenaar commented on config/data/asr.yaml
> -  trace_properties:
Omdat het toch wel om data-achtige eigenschappen vind, vind ik het logischer om ze ook in de data yaml te kunnen specificeren (ook bij de source filters in de buurt)

2024-02-08 14:34 UTC, cdwagenaar commented on lrbenchmark/utils.py
> +            m_a.id != m_b.id or not measurement_pair.is_same_source)
aangepast en een __eq__ methode voor measurements aangepast

2024-02-08 14:49 UTC, cdwagenaar commented on config/data/asr.yaml
> -    auto: ja
Ik vind dit wel een apart taakje waard, omdat er dan idealiter ook een bestand komt waar deze eigenschappen van de zaaksvergelijken in staan

2024-02-09 14:07 UTC, SimoneAriens commented on lrbenchmark/data/dataset.py
> +                                       relevant_properties=self.relevant_properties),
is het per se nodig om de relevant properties in de dataset mee te geven? Andere optie zou zijn om de waarde via de config bij get_trace_reference_properties te krijgen

2024-02-09 14:34 UTC, SimoneAriens commented on lrbenchmark/utils.py
> +            complies_with_filter_requirements(properties[0], m_b.extra)) and m_a != m_b
zou dit niet toch m_a.source.id!=m_b.source.id or m_a.sample.id!=m_b.sample.id moeten zijn. Want als nu alleen de measurement id anders is dan klopt dit, maar dan kan je nog steeds de 15s en 30s variant van dezelfde sample hebben

2024-02-09 14:37 UTC, SimoneAriens commented on run.py
> +    trace_reference_properties = [get_trace_reference_properties(config_resolved['dataset'])[0]]
dit kan gewoon 'get_trace_reference_properties(config_resolved['dataset'])' zijn ipv met de [] en [0]

2024-02-09 15:12 UTC, SimoneAriens commented on tests/test_pairing.py
> +                              trace_reference_properties=({'property': 'trace'}, {'property': 'reference'}))
zijn dit voorbeeld properties? Want anders zegt dit allemaal niet zoveel toch?

2024-02-12 07:42 UTC, cdwagenaar commented on lrbenchmark/data/dataset.py
> +                                       relevant_properties=self.relevant_properties),
Ik denk dat de codewise idd netter is, maar zou je dan de relevant_properties in de lrbenchmark yaml zetten?

2024-02-12 07:49 UTC, cdwagenaar commented on lrbenchmark/utils.py
> +            complies_with_filter_requirements(properties[0], m_b.extra)) and m_a != m_b
Hmm, maar ik heb nu de measurement id gelijk aan de duur gezet (dus 15 of 30), dus met m_a!=m_b voorkom je nu dat je twee 'duur'varianten van dezelfde sample krijgt, met m_a.source.id!=m_b.source.id or m_a.sample.id!=m_b.sample.id dwing je dat niet af.

2024-02-12 07:49 UTC, cdwagenaar commented on tests/test_pairing.py
> +                              trace_reference_properties=({'property': 'trace'}, {'property': 'reference'}))
Ja klopt idd voorbeeld properties om even ergens op te kunnen filteren

2024-02-12 07:59 UTC, rolfypma-nfi commented on lrbenchmark/utils.py
> +            complies_with_filter_requirements(properties[0], m_b.extra)) and m_a != m_b
dat dwing je toch juist af met niet zelfde sample_id of niet zelfde source id? duration=id lijkt me zoiezo erg asr specifiek, beter niet als algemeen gegeven gebruiken! :)

2024-02-12 15:11 UTC, rolfypma-nfi requested changes

2024-02-12 15:11 UTC, rolfypma-nfi commented on lrbenchmark/load.py
> +def get_trace_reference_properties(dataset: Dataset) -> \
mooier om het hier voor de hele dataset te doen, en de aanroepende partij de holdout sources te laten selecteren?

2024-02-12 15:11 UTC, rolfypma-nfi commented on lrbenchmark/load.py
> +def get_trace_reference_properties(dataset: Dataset) -> \
get_filter_combination_values oid?

2024-02-12 15:11 UTC, rolfypma-nfi commented on lrbenchmark/load.py
> +        List[Optional[Tuple[Mapping[str, str], Mapping[str, str]]]]:
waarom een lijst van None toestaan, en niet gewoon een lege lijst?

2024-02-12 15:11 UTC, rolfypma-nfi commented on lrbenchmark/load.py
> +        [json.dumps({relevant_prop: prop.get(relevant_prop) for relevant_prop in dataset.relevant_properties})
waarom de json dumps en loads?

2024-02-12 15:11 UTC, rolfypma-nfi commented on lrbenchmark/load.py
> +    trace_reference_properties = list(itertools.combinations_with_replacement(holdout_properties, 2))
zo krijg je toch teveel property combinaties? Bijvoorbeeld alles van een source met zichzelf?

2024-02-12 15:11 UTC, rolfypma-nfi commented on lrbenchmark/utils.py
> +            complies_with_filter_requirements(properties[1], m_a.extra) and
voor de veiligheid zou ik hier de tweede 'and' ook haakjes eromheen geven

2024-02-12 15:11 UTC, rolfypma-nfi commented on run.py
> +    trace_reference_properties = [get_trace_reference_properties(config_resolved['dataset'])[0]]
wat is de reden dat deze niet aan de exp.parameter meegegeven wordt? en de rest wel? terwijl het wel als parameter behandeld wordt hier beneden?

2024-02-13 09:31 UTC, cdwagenaar commented on lrbenchmark/load.py
> +        List[Optional[Tuple[Mapping[str, str], Mapping[str, str]]]]:
Omdat de lijst niet leeg mag zijn op het moment dat je de experimenten in gaat

2024-02-13 09:33 UTC, cdwagenaar commented on lrbenchmark/load.py
> +        [json.dumps({relevant_prop: prop.get(relevant_prop) for relevant_prop in dataset.relevant_properties})
zodat we een set kunnen maken van de dict met properties

2024-02-13 10:20 UTC, cdwagenaar commented on lrbenchmark/load.py
> +    trace_reference_properties = list(itertools.combinations_with_replacement(holdout_properties, 2))
Ja hier hadden we wel expliciet voor gekozen, ik ga er nog met david doorheen lopen, dus voorstel om het nu zo te laten en later eventueel aan te passen?

2024-02-13 10:24 UTC, cdwagenaar commented on run.py
> +    trace_reference_properties = [get_trace_reference_properties(config_resolved['dataset'])[0]]
Volgens mij zijn de waardes van exp.parameter hetzelfde over runs, maar wordt er over de waardes in 'parameters' juist geitereerd per experiment en dat is wat we ook willen met de verschillende 'properties'

2024-02-13 16:17 UTC, rolfypma-nfi commented on lrbenchmark/load.py
> +        List[Optional[Tuple[Mapping[str, str], Mapping[str, str]]]]:
zou een tuple van twee lege mappings dan niet werken? Dan hoef je geen ifs in de code te hebben, maar is er gewoon een optie waarbij alle measurements altijd slagen?

2024-02-13 16:27 UTC, rolfypma-nfi commented on tests/test_load.py
> +    expected_properties = list(combinations_with_replacement(properties_of_holdout_set, r=2))
hier is
properties_of_holdout_set = 
 [{'property1': 'yes', 'property2': 'no'}, 
{'property1': 'no', 'property2': 'yes'}]

Dan zou ik verwachten dat we maar 1 type paar hoeven te bekijken, namelijk een yes,no-no,yes. In de huidige code worden ook no,yes-no,yes paren vergeleken en yes,no-yes,no. 

Side note - ik vind een test inzichtelijker als ook expected_properties in dit geval uitgeschreven is (net als properties_of_holdout_set) - dan is meteen duidelijk wat het verwachte/gewenste gedrag is.

2024-02-14 09:42 UTC, cdwagenaar commented on tests/test_load.py
> +    expected_properties = list(combinations_with_replacement(properties_of_holdout_set, r=2))
Ja over die combinaties, ik ga er morgen met simone nog even naar kijken

2024-02-15 14:40 UTC, rolfypma-nfi approved these changes

2024-02-16 09:00 UTC, merged